;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Sat Jan 11 2025
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================

CODE    SEGMENT PUBLIC 'CODE'
        ASSUME CS:CODE
porta       EQU  68h          ; Address of Port A  68 & F8 ==68
portb       EQU  6Ah          ; Address of Port B
portc       EQU  6Ch          ; Address of Port C
controlport EQU  6Eh         ; Address of Control Port
START:



main:
 mov al,88h ; set values for control port (100: for mode a 0 ,0 :A port is output, 1: c upper is input,0:b mode0, 0 :b  port is output,0: c lowerpart dont care set  as 0  )
 out controlport,al

SCANNING_KEYBOARDS:
  ;FIRSTCOLUMN 
  ; sending for first column
  mov al,00000100b   
  out portb, al 
  ; receiving for first column 
  in al, portc
  and al,0fh ; check if any data was sent on this column
  jnz column1 ; key stroke detected, jump to figure the row (exact key)

 ;SECOUND COLUMN 
 ; sending for second column
  mov al,00000010b   
  out portb, al 
  ; receiving for second column 
  in al, portc
  and al,0fh ; check if any data was sent on this column
  jnz column2 ; key stroke detected, jump to figure the row (exact key)

 ;THIRD COLUMN 
 ; sending for third column
  mov al,00000001b   
  out portb, al 
  ; receiving for third column 
  in al, portc
  and al,0fh ; check if any data was sent on this column
  jnz column3 ; key stroke detected, jump to figure the row (exact key)

 jmp SCANNING_KEYBOARDS
 
column1:
 ;num1
 cmp al,0001b
 jnz num4
 mov al,110b
 out porta, al
 jmp SCANNING_KEYBOARDS
 num4:
  cmp al,0010b
 jnz num7
 mov al,1100110b
 out porta, al
 jmp SCANNING_KEYBOARDS
 
 num7:
  cmp al,0100b
 jnz SCANNING_KEYBOARDS
 mov al,0000111b
 out porta, al
 jmp SCANNING_KEYBOARDS

column2:
  ;num2
 cmp al,0001b
 jnz num5
 mov al,1011011b
 out porta, al
 jmp SCANNING_KEYBOARDS
 num5:
  cmp al,0010b
 jnz num8
 mov al,1101101b
 out porta, al
 jmp SCANNING_KEYBOARDS
num8:
  cmp al,0100b
 jnz num0
 mov al,1111111b
 out porta, al
 jmp SCANNING_KEYBOARDS
 num0:
  cmp al,1000b
 jnz SCANNING_KEYBOARDS
 mov al,0111111b
 out porta, al
 jmp SCANNING_KEYBOARDS

column3:
 ;num3
 cmp al,0001b
 jnz num6
 mov al,1001111b
 out porta, al
 jmp SCANNING_KEYBOARDS
 num6:
  cmp al,0010b
 jnz num9
 mov al,1111101b
 out porta, al
 jmp SCANNING_KEYBOARDS
 
 num9:
  cmp al,0100b
 jnz SCANNING_KEYBOARDS
 mov al,1101111b
 out porta, al
 jmp SCANNING_KEYBOARDS

ENDLESS:
        JMP ENDLESS
CODE    ENDS
        END START
